export async function GET() {
  const jobs = [
    {
      id: 1,
      company: "Photosnap",
      logo: "/images/photosnap.svg",
      logoColor: "#1E1F26",
      isNew: true,
      featured: true,
      position: "Senior Frontend Developer",
      role: "Frontend",
      level: "Senior",
      postedAt: "1d ago",
      contract: "Full Time",
      location: "USA Only",
      languages: ["HTML", "CSS", "JavaScript"],
      tools: [],
      description:
        "We are looking for a Senior Frontend Developer with extensive experience in building modern web applications. You will work closely with our design team to implement pixel-perfect UIs and ensure the best user experience possible.",
    },
    {
      id: 2,
      company: "Manage",
      logo: "/images/manage.svg",
      logoColor: "#FF5050",
      isNew: true,
      featured: true,
      position: "Fullstack Developer",
      role: "Fullstack",
      level: "Midweight",
      postedAt: "1d ago",
      contract: "Part Time",
      location: "Remote",
      languages: ["Python"],
      tools: ["React"],
      description:
        "Manage is looking for a talented Fullstack Developer to join our growing team. You will be responsible for both frontend and backend development, building scalable and maintainable systems.",
    },
    {
      id: 3,
      company: "Account",
      logo: "/images/account.svg",
      logoColor: "#6B5EA8",
      isNew: true,
      featured: false,
      position: "Junior Frontend Developer",
      role: "Frontend",
      level: "Junior",
      postedAt: "2d ago",
      contract: "Part Time",
      location: "USA Only",
      languages: ["JavaScript"],
      tools: ["React", "Sass"],
      description:
        "Account is seeking a motivated Junior Frontend Developer to join our dynamic team. This is a great opportunity to grow your skills while working on exciting real-world projects.",
    },
    {
      id: 4,
      company: "MyHome",
      logo: "/images/myhome.svg",
      logoColor: "#18A4A4",
      isNew: false,
      featured: false,
      position: "Junior Frontend Developer",
      role: "Frontend",
      level: "Junior",
      postedAt: "5d ago",
      contract: "Contract",
      location: "USA Only",
      languages: ["CSS", "JavaScript"],
      tools: [],
      description:
        "MyHome is on the lookout for a passionate Junior Frontend Developer. You'll collaborate with a small, agile team to build intuitive and beautiful user interfaces for our home management platform.",
    },
    {
      id: 5,
      company: "Loop Studios",
      logo: "/images/loop-studios.svg",
      logoColor: "#3A3C4E",
      isNew: false,
      featured: false,
      position: "Software Engineer",
      role: "Fullstack",
      level: "Midweight",
      postedAt: "1w ago",
      contract: "Full Time",
      location: "Worldwide",
      languages: ["JavaScript"],
      tools: ["Sass", "Ruby"],
      description:
        "Loop Studios is seeking a Midweight Software Engineer who thrives in a collaborative environment. You will be working on our core product, helping shape the architecture and improving performance.",
    },
    {
      id: 6,
      company: "FaceIt",
      logo: "/images/faceit.svg",
      logoColor: "#FF6B35",
      isNew: false,
      featured: false,
      position: "Junior Backend Developer",
      role: "Backend",
      level: "Junior",
      postedAt: "2w ago",
      contract: "Full Time",
      location: "UK Only",
      languages: ["Ruby"],
      tools: ["RoR"],
      description:
        "FaceIt is looking for a Junior Backend Developer to help build and maintain our gaming platform's backend services. You will work with our senior engineers to develop scalable APIs and microservices.",
    },
    {
      id: 7,
      company: "Shortly",
      logo: "/images/shortly.svg",
      logoColor: "#249F7C",
      isNew: false,
      featured: false,
      position: "Junior Developer",
      role: "Frontend",
      level: "Junior",
      postedAt: "2w ago",
      contract: "Full Time",
      location: "Worldwide",
      languages: ["HTML", "JavaScript"],
      tools: ["Sass"],
      description:
        "Shortly is expanding its engineering team and is looking for a Junior Developer with a passion for clean code and great UI. You will help develop new features and improve existing ones on our URL shortening platform.",
    },
    {
      id: 8,
      company: "Insure",
      logo: "/images/insure.svg",
      logoColor: "#A74FF0",
      isNew: false,
      featured: false,
      position: "Junior Frontend Developer",
      role: "Frontend",
      level: "Junior",
      postedAt: "2w ago",
      contract: "Full Time",
      location: "USA Only",
      languages: ["JavaScript"],
      tools: ["Vue", "Sass"],
      description:
        "Insure is seeking a Junior Frontend Developer to join our product team. You will work on building accessible and performant insurance dashboards for our clients.",
    },
    {
      id: 9,
      company: "Eyecam Co.",
      logo: "/images/eyecam-co.svg",
      logoColor: "#4A90D9",
      isNew: false,
      featured: false,
      position: "Full Stack Engineer",
      role: "Fullstack",
      level: "Midweight",
      postedAt: "3w ago",
      contract: "Full Time",
      location: "Worldwide",
      languages: ["JavaScript", "Python"],
      tools: ["Django"],
      description:
        "Eyecam Co. is hiring a Full Stack Engineer to work on our computer vision platform. You'll build APIs, design data pipelines, and contribute to our React-based dashboard.",
    },
    {
      id: 10,
      company: "The Air Filter Company",
      logo: "/images/the-air-filter-company.svg",
      logoColor: "#FF9500",
      isNew: false,
      featured: false,
      position: "Front-end Dev",
      role: "Frontend",
      level: "Junior",
      postedAt: "1mo ago",
      contract: "Part Time",
      location: "Worldwide",
      languages: ["JavaScript"],
      tools: ["React", "Sass"],
      description:
        "The Air Filter Company is looking for a Front-end Developer to help build our e-commerce platform. You will be responsible for implementing new features and maintaining the existing codebase.",
    },
  ];

  return Response.json(jobs);
}
